/* ============================================================
   CORPUS — phrases réelles, adultes, triées par fréquence d'usage.
   Aucune phrase du type "le chat boit du lait".
   lvl 1..6 = ordre d'introduction, pas une note.
   ============================================================ */

const CORPUS = [
  // ---------- N1 · SURVIE : les 100 premières minutes ----------
  { lvl: 1, es: "Hola, ¿qué tal?", fr: "Salut, ça va ?", tag: "social" },
  { lvl: 1, es: "Me llamo Georges.", fr: "Je m'appelle Georges.", tag: "social" },
  { lvl: 1, es: "¿Cómo te llamas?", fr: "Comment tu t'appelles ?", tag: "social" },
  { lvl: 1, es: "Soy francés.", fr: "Je suis français.", tag: "social", note: "ser = identité permanente" },
  { lvl: 1, es: "No soy de aquí.", fr: "Je ne suis pas d'ici.", tag: "social" },
  { lvl: 1, es: "¿De dónde eres?", fr: "Tu viens d'où ?", tag: "social" },
  { lvl: 1, es: "Encantado.", fr: "Enchanté.", tag: "social" },
  { lvl: 1, es: "No hablo bien español, pero estoy aprendiendo.", fr: "Je ne parle pas bien espagnol, mais j'apprends.", tag: "meta", note: "Ta phrase-bouclier. Elle désamorce tout." },
  { lvl: 1, es: "¿Puedes repetir, por favor?", fr: "Tu peux répéter, s'il te plaît ?", tag: "meta" },
  { lvl: 1, es: "Más despacio, por favor.", fr: "Plus lentement, s'il te plaît.", tag: "meta" },
  { lvl: 1, es: "No entiendo.", fr: "Je ne comprends pas.", tag: "meta" },
  { lvl: 1, es: "¿Qué significa eso?", fr: "Ça veut dire quoi ?", tag: "meta" },
  { lvl: 1, es: "¿Cómo se dice «ordinateur» en español?", fr: "Comment on dit « ordinateur » en espagnol ?", tag: "meta", note: "La phrase qui te fait apprendre sans prof." },
  { lvl: 1, es: "Ahora entiendo.", fr: "Maintenant je comprends.", tag: "meta" },
  { lvl: 1, es: "Tengo treinta años.", fr: "J'ai trente ans.", tag: "base", note: "L'âge se dit avec TENER, pas ser." },
  { lvl: 1, es: "Tengo hambre.", fr: "J'ai faim.", tag: "base" },
  { lvl: 1, es: "Tengo sed.", fr: "J'ai soif.", tag: "base" },
  { lvl: 1, es: "Tengo frío.", fr: "J'ai froid.", tag: "base" },
  { lvl: 1, es: "Tengo que irme.", fr: "Je dois y aller.", tag: "base", note: "tener que + infinitif = devoir" },
  { lvl: 1, es: "Quiero un café, por favor.", fr: "Je veux un café, s'il te plaît.", tag: "resto" },
  { lvl: 1, es: "Quisiera reservar una mesa para dos.", fr: "Je voudrais réserver une table pour deux.", tag: "resto" },
  { lvl: 1, es: "¿Cuánto cuesta?", fr: "Combien ça coûte ?", tag: "achat" },
  { lvl: 1, es: "Es demasiado caro.", fr: "C'est trop cher.", tag: "achat" },
  { lvl: 1, es: "¿Aceptan tarjeta?", fr: "Vous acceptez la carte ?", tag: "achat" },
  { lvl: 1, es: "La cuenta, por favor.", fr: "L'addition, s'il te plaît.", tag: "resto" },
  { lvl: 1, es: "¿Dónde está el baño?", fr: "Où sont les toilettes ?", tag: "survie" },
  { lvl: 1, es: "Estoy perdido.", fr: "Je suis perdu.", tag: "survie", note: "estar = état temporaire" },
  { lvl: 1, es: "¿Cómo llego al centro?", fr: "Comment j'arrive au centre ?", tag: "survie" },
  { lvl: 1, es: "Está muy lejos.", fr: "C'est très loin.", tag: "survie" },
  { lvl: 1, es: "Está aquí al lado.", fr: "C'est juste à côté.", tag: "survie" },
  { lvl: 1, es: "Voy a casa.", fr: "Je rentre à la maison.", tag: "base" },
  { lvl: 1, es: "¿Vamos?", fr: "On y va ?", tag: "base" },
  { lvl: 1, es: "Vamos a tomar algo.", fr: "On va boire un truc.", tag: "social" },
  { lvl: 1, es: "¿Qué hora es?", fr: "Quelle heure est-il ?", tag: "base" },
  { lvl: 1, es: "Son las tres y media.", fr: "Il est trois heures et demie.", tag: "base" },
  { lvl: 1, es: "Llego tarde.", fr: "Je suis en retard.", tag: "base" },
  { lvl: 1, es: "Nos vemos mañana.", fr: "On se voit demain.", tag: "social" },
  { lvl: 1, es: "Hasta luego.", fr: "À plus tard.", tag: "social" },
  { lvl: 1, es: "Gracias, muy amable.", fr: "Merci, très aimable.", tag: "social" },
  { lvl: 1, es: "De nada.", fr: "De rien.", tag: "social" },
  { lvl: 1, es: "Perdona, ¿me ayudas?", fr: "Excuse-moi, tu m'aides ?", tag: "survie" },
  { lvl: 1, es: "Claro que sí.", fr: "Bien sûr que oui.", tag: "social" },
  { lvl: 1, es: "No pasa nada.", fr: "Il n'y a pas de souci.", tag: "social" },
  { lvl: 1, es: "Me gusta mucho.", fr: "J'aime beaucoup.", tag: "base", note: "Littéralement « ça me plaît ». Le sujet est la chose, pas toi." },
  { lvl: 1, es: "No me gusta nada.", fr: "Je n'aime pas du tout.", tag: "base" },
  { lvl: 1, es: "¿Te gusta?", fr: "Ça te plaît ?", tag: "base" },
  { lvl: 1, es: "Estoy cansado.", fr: "Je suis fatigué.", tag: "base" },
  { lvl: 1, es: "Estoy bien, gracias.", fr: "Je vais bien, merci.", tag: "social" },
  { lvl: 1, es: "¿Qué es esto?", fr: "C'est quoi, ça ?", tag: "base" },
  { lvl: 1, es: "¿Hablas francés o inglés?", fr: "Tu parles français ou anglais ?", tag: "meta" },

  // ---------- N2 · QUOTIDIEN ----------
  { lvl: 2, es: "¿A qué te dedicas?", fr: "Tu fais quoi dans la vie ?", tag: "social", note: "Plus naturel que « ¿cuál es tu trabajo? »" },
  { lvl: 2, es: "Trabajo desde casa.", fr: "Je travaille depuis chez moi.", tag: "travail" },
  { lvl: 2, es: "Me levanto a las siete.", fr: "Je me lève à sept heures.", tag: "quotidien" },
  { lvl: 2, es: "Desayuno un café y nada más.", fr: "Je prends juste un café au petit-déj.", tag: "quotidien" },
  { lvl: 2, es: "Hoy no tengo tiempo.", fr: "Aujourd'hui je n'ai pas le temps.", tag: "quotidien" },
  { lvl: 2, es: "¿Puedes ayudarme con esto?", fr: "Tu peux m'aider avec ça ?", tag: "quotidien" },
  { lvl: 2, es: "Lo hago yo.", fr: "Je le fais, moi.", tag: "quotidien" },
  { lvl: 2, es: "No sé todavía.", fr: "Je ne sais pas encore.", tag: "quotidien" },
  { lvl: 2, es: "Creo que sí.", fr: "Je crois que oui.", tag: "opinion" },
  { lvl: 2, es: "Depende.", fr: "Ça dépend.", tag: "opinion" },
  { lvl: 2, es: "¿Por qué no?", fr: "Pourquoi pas ?", tag: "social" },
  { lvl: 2, es: "Porque no me apetece.", fr: "Parce que je n'ai pas envie.", tag: "social" },
  { lvl: 2, es: "Me da igual.", fr: "Ça m'est égal.", tag: "opinion" },
  { lvl: 2, es: "Ya lo sé.", fr: "Je sais déjà.", tag: "quotidien" },
  { lvl: 2, es: "Todavía no.", fr: "Pas encore.", tag: "quotidien" },
  { lvl: 2, es: "Otra vez.", fr: "Encore une fois.", tag: "quotidien" },
  { lvl: 2, es: "Un momento, ahora vengo.", fr: "Une seconde, j'arrive.", tag: "quotidien" },
  { lvl: 2, es: "Espérame aquí.", fr: "Attends-moi ici.", tag: "quotidien" },
  { lvl: 2, es: "¿Me pasas el agua?", fr: "Tu me passes l'eau ?", tag: "resto" },
  { lvl: 2, es: "Necesito dormir.", fr: "J'ai besoin de dormir.", tag: "quotidien" },
  { lvl: 2, es: "Tengo mucho trabajo esta semana.", fr: "J'ai beaucoup de travail cette semaine.", tag: "travail" },
  { lvl: 2, es: "¿Qué te parece?", fr: "Qu'est-ce que t'en penses ?", tag: "opinion" },
  { lvl: 2, es: "Me parece buena idea.", fr: "Ça me paraît une bonne idée.", tag: "opinion" },
  { lvl: 2, es: "No estoy de acuerdo.", fr: "Je ne suis pas d'accord.", tag: "opinion" },
  { lvl: 2, es: "Tienes razón.", fr: "Tu as raison.", tag: "opinion" },
  { lvl: 2, es: "Estás equivocado.", fr: "Tu te trompes.", tag: "opinion" },
  { lvl: 2, es: "Déjame pensarlo.", fr: "Laisse-moi y réfléchir.", tag: "opinion" },
  { lvl: 2, es: "¿Te puedo llamar más tarde?", fr: "Je peux t'appeler plus tard ?", tag: "quotidien" },
  { lvl: 2, es: "Mándame un mensaje.", fr: "Envoie-moi un message.", tag: "quotidien" },
  { lvl: 2, es: "Estoy en camino.", fr: "Je suis en route.", tag: "quotidien" },
  { lvl: 2, es: "¿Qué tal el fin de semana?", fr: "C'était comment, le week-end ?", tag: "social" },
  { lvl: 2, es: "Salimos el sábado por la noche.", fr: "On sort samedi soir.", tag: "social" },
  { lvl: 2, es: "Me quedo en casa.", fr: "Je reste à la maison.", tag: "quotidien" },
  { lvl: 2, es: "Hace mucho calor hoy.", fr: "Il fait très chaud aujourd'hui.", tag: "quotidien", note: "La météo se dit avec HACER." },
  { lvl: 2, es: "Está lloviendo.", fr: "Il pleut.", tag: "quotidien" },
  { lvl: 2, es: "Voy a comprar pan.", fr: "Je vais acheter du pain.", tag: "achat" },
  { lvl: 2, es: "¿Tienes cambio?", fr: "Tu as de la monnaie ?", tag: "achat" },
  { lvl: 2, es: "Póngame dos, por favor.", fr: "Mettez-m'en deux, s'il vous plaît.", tag: "achat" },
  { lvl: 2, es: "¿Algo más?", fr: "Autre chose ?", tag: "achat" },
  { lvl: 2, es: "Nada más, gracias.", fr: "Rien d'autre, merci.", tag: "achat" },
  { lvl: 2, es: "Está muy rico.", fr: "C'est très bon.", tag: "resto", note: "Pour la bouffe on dit « rico », pas « bueno »." },
  { lvl: 2, es: "No como carne.", fr: "Je ne mange pas de viande.", tag: "resto" },
  { lvl: 2, es: "Soy alérgico a los frutos secos.", fr: "Je suis allergique aux fruits à coque.", tag: "resto" },
  { lvl: 2, es: "¿Me recomiendas algo?", fr: "Tu me recommandes quelque chose ?", tag: "resto" },
  { lvl: 2, es: "Lo mismo para mí.", fr: "La même chose pour moi.", tag: "resto" },
  { lvl: 2, es: "Invito yo.", fr: "C'est moi qui invite.", tag: "social" },
  { lvl: 2, es: "¿Nos tomamos una caña?", fr: "On se prend une bière ?", tag: "social", note: "« caña » = demi pression, Espagne." },
  { lvl: 2, es: "¿Te apuntas?", fr: "Tu es partant ?", tag: "social" },
  { lvl: 2, es: "Estoy buscando piso.", fr: "Je cherche un appart.", tag: "quotidien" },
  { lvl: 2, es: "No me funciona el móvil.", fr: "Mon téléphone ne marche pas.", tag: "quotidien" },

  // ---------- N3 · PASSÉ & OPINIONS ----------
  { lvl: 3, es: "Ayer fui al cine.", fr: "Hier je suis allé au ciné.", tag: "passé" },
  { lvl: 3, es: "¿Qué hiciste el fin de semana?", fr: "T'as fait quoi ce week-end ?", tag: "passé" },
  { lvl: 3, es: "No hice nada especial.", fr: "J'ai rien fait de spécial.", tag: "passé" },
  { lvl: 3, es: "Llegué muy tarde a casa.", fr: "Je suis rentré très tard.", tag: "passé" },
  { lvl: 3, es: "Comimos en un sitio increíble.", fr: "On a mangé dans un endroit incroyable.", tag: "passé" },
  { lvl: 3, es: "Me encantó la película.", fr: "J'ai adoré le film.", tag: "opinion" },
  { lvl: 3, es: "No me gustó nada el final.", fr: "J'ai pas du tout aimé la fin.", tag: "opinion" },
  { lvl: 3, es: "Estuve enfermo toda la semana.", fr: "J'ai été malade toute la semaine.", tag: "passé" },
  { lvl: 3, es: "Le dije que no.", fr: "Je lui ai dit non.", tag: "passé" },
  { lvl: 3, es: "Me lo contó todo.", fr: "Il m'a tout raconté.", tag: "passé" },
  { lvl: 3, es: "Antes vivía en París.", fr: "Avant je vivais à Paris.", tag: "passé", note: "Imparfait = habitude / décor." },
  { lvl: 3, es: "Cuando era pequeño, jugaba al fútbol.", fr: "Quand j'étais petit, je jouais au foot.", tag: "passé" },
  { lvl: 3, es: "Siempre hacíamos lo mismo.", fr: "On faisait toujours la même chose.", tag: "passé" },
  { lvl: 3, es: "He estado en España tres veces.", fr: "Je suis allé en Espagne trois fois.", tag: "passé" },
  { lvl: 3, es: "Todavía no he terminado.", fr: "Je n'ai pas encore fini.", tag: "passé" },
  { lvl: 3, es: "¿Has probado esto alguna vez?", fr: "T'as déjà goûté ça ?", tag: "passé" },
  { lvl: 3, es: "Acabo de llegar.", fr: "Je viens d'arriver.", tag: "passé", note: "acabar de = venir de" },
  { lvl: 3, es: "Llevo dos años estudiando.", fr: "Ça fait deux ans que j'étudie.", tag: "passé", note: "llevar + gérondif : structure ultra espagnole, aucun équivalent direct." },
  { lvl: 3, es: "Hace un mes que no lo veo.", fr: "Ça fait un mois que je ne le vois pas.", tag: "passé" },
  { lvl: 3, es: "Se me ha olvidado.", fr: "J'ai oublié.", tag: "passé", note: "Littéralement « ça s'est oublié à moi ». L'espagnol déresponsabilise." },
  { lvl: 3, es: "Se me ha roto el móvil.", fr: "J'ai cassé mon téléphone.", tag: "passé" },
  { lvl: 3, es: "En mi opinión, es un error.", fr: "À mon avis, c'est une erreur.", tag: "opinion" },
  { lvl: 3, es: "La verdad es que no lo sé.", fr: "La vérité c'est que je ne sais pas.", tag: "opinion" },
  { lvl: 3, es: "Lo que pasa es que no tengo tiempo.", fr: "Le truc c'est que je n'ai pas le temps.", tag: "opinion" },
  { lvl: 3, es: "Por un lado sí, pero por otro no.", fr: "D'un côté oui, mais de l'autre non.", tag: "opinion" },
  { lvl: 3, es: "Sin embargo, no cambia nada.", fr: "Cependant, ça ne change rien.", tag: "connecteur" },
  { lvl: 3, es: "Además, cuesta demasiado.", fr: "En plus, ça coûte trop cher.", tag: "connecteur" },
  { lvl: 3, es: "Por eso lo dejé.", fr: "C'est pour ça que j'ai arrêté.", tag: "connecteur" },
  { lvl: 3, es: "O sea, que no vienes.", fr: "Autrement dit, tu ne viens pas.", tag: "connecteur" },
  { lvl: 3, es: "Es decir, tenemos un problema.", fr: "C'est-à-dire qu'on a un problème.", tag: "connecteur" },
  { lvl: 3, es: "De todas formas, da igual.", fr: "De toute façon, peu importe.", tag: "connecteur" },
  { lvl: 3, es: "A lo mejor viene mañana.", fr: "Peut-être qu'il vient demain.", tag: "opinion" },
  { lvl: 3, es: "Seguramente está durmiendo.", fr: "Il dort sûrement.", tag: "opinion" },
  { lvl: 3, es: "Me parece que se ha ido.", fr: "J'ai l'impression qu'il est parti.", tag: "opinion" },
  { lvl: 3, es: "No tengo ni idea.", fr: "Je n'en ai aucune idée.", tag: "opinion" },
  { lvl: 3, es: "Me lo pensé mucho antes de decidir.", fr: "J'y ai beaucoup réfléchi avant de décider.", tag: "passé" },
  { lvl: 3, es: "Al final decidí quedarme.", fr: "Finalement j'ai décidé de rester.", tag: "passé" },
  { lvl: 3, es: "Fue una locura.", fr: "C'était de la folie.", tag: "récit" },
  { lvl: 3, es: "Valió la pena.", fr: "Ça valait le coup.", tag: "récit" },
  { lvl: 3, es: "Fue lo mejor que me pasó.", fr: "C'est la meilleure chose qui me soit arrivée.", tag: "récit" },
  { lvl: 3, es: "Me arrepiento de no haberlo hecho.", fr: "Je regrette de ne pas l'avoir fait.", tag: "récit" },
  { lvl: 3, es: "Aprendí mucho de eso.", fr: "J'ai beaucoup appris de ça.", tag: "récit" },
  { lvl: 3, es: "Cambió mi forma de ver las cosas.", fr: "Ça a changé ma façon de voir les choses.", tag: "récit" },
  { lvl: 3, es: "Al principio no entendía nada.", fr: "Au début je ne comprenais rien.", tag: "récit" },
  { lvl: 3, es: "Poco a poco fui mejorando.", fr: "Petit à petit je me suis amélioré.", tag: "récit" },

  // ---------- N4 · FUTUR, CONDITIONNEL, SUBJONCTIF ----------
  { lvl: 4, es: "Mañana voy a empezar.", fr: "Demain je vais commencer.", tag: "futur" },
  { lvl: 4, es: "Te llamo esta noche.", fr: "Je t'appelle ce soir.", tag: "futur", note: "Le présent suffit pour le futur proche." },
  { lvl: 4, es: "El año que viene me mudo.", fr: "L'année prochaine je déménage.", tag: "futur" },
  { lvl: 4, es: "Lo haré mañana sin falta.", fr: "Je le ferai demain sans faute.", tag: "futur" },
  { lvl: 4, es: "Ya veremos.", fr: "On verra.", tag: "futur" },
  { lvl: 4, es: "¿Qué harías tú en mi lugar?", fr: "Tu ferais quoi à ma place ?", tag: "conditionnel" },
  { lvl: 4, es: "Yo que tú, no iría.", fr: "À ta place, je n'irais pas.", tag: "conditionnel" },
  { lvl: 4, es: "Me gustaría verte pronto.", fr: "J'aimerais te voir bientôt.", tag: "conditionnel" },
  { lvl: 4, es: "Podrías avisarme antes.", fr: "Tu pourrais me prévenir avant.", tag: "conditionnel" },
  { lvl: 4, es: "Deberías descansar.", fr: "Tu devrais te reposer.", tag: "conditionnel" },
  { lvl: 4, es: "Sería mejor esperar.", fr: "Ce serait mieux d'attendre.", tag: "conditionnel" },
  { lvl: 4, es: "Si tuviera dinero, viajaría más.", fr: "Si j'avais de l'argent, je voyagerais plus.", tag: "conditionnel" },
  { lvl: 4, es: "Si hubiera sabido, no habría venido.", fr: "Si j'avais su, je ne serais pas venu.", tag: "conditionnel" },
  { lvl: 4, es: "Quiero que vengas conmigo.", fr: "Je veux que tu viennes avec moi.", tag: "subjonctif", note: "Volonté sur autrui → subjonctif. Exactement comme en français." },
  { lvl: 4, es: "Espero que todo salga bien.", fr: "J'espère que tout se passera bien.", tag: "subjonctif" },
  { lvl: 4, es: "Ojalá tengas razón.", fr: "Pourvu que tu aies raison.", tag: "subjonctif", note: "« Ojalá » vient de l'arabe : « si Dieu le veut »." },
  { lvl: 4, es: "Es importante que lo sepas.", fr: "C'est important que tu le saches.", tag: "subjonctif" },
  { lvl: 4, es: "No creo que sea buena idea.", fr: "Je ne crois pas que ce soit une bonne idée.", tag: "subjonctif" },
  { lvl: 4, es: "Cuando llegues, avísame.", fr: "Quand tu arrives, préviens-moi.", tag: "subjonctif", note: "Futur incertain après « cuando » → subjonctif. Piège classique." },
  { lvl: 4, es: "Antes de que se me olvide...", fr: "Avant que j'oublie...", tag: "subjonctif" },
  { lvl: 4, es: "Para que lo entiendas mejor.", fr: "Pour que tu comprennes mieux.", tag: "subjonctif" },
  { lvl: 4, es: "Aunque sea difícil, hay que intentarlo.", fr: "Même si c'est difficile, il faut essayer.", tag: "subjonctif" },
  { lvl: 4, es: "Hay que hacerlo ya.", fr: "Il faut le faire maintenant.", tag: "obligation" },
  { lvl: 4, es: "Tenemos que hablar.", fr: "Il faut qu'on parle.", tag: "obligation" },
  { lvl: 4, es: "No hace falta.", fr: "Ce n'est pas nécessaire.", tag: "obligation" },
  { lvl: 4, es: "Es mejor que te vayas.", fr: "Il vaut mieux que tu partes.", tag: "subjonctif" },
  { lvl: 4, es: "Dile que me llame.", fr: "Dis-lui de m'appeler.", tag: "impératif" },
  { lvl: 4, es: "No le digas nada a nadie.", fr: "Ne dis rien à personne.", tag: "impératif" },
  { lvl: 4, es: "Haz lo que quieras.", fr: "Fais ce que tu veux.", tag: "impératif" },
  { lvl: 4, es: "Ven aquí un momento.", fr: "Viens ici une seconde.", tag: "impératif" },
  { lvl: 4, es: "Déjalo, no importa.", fr: "Laisse tomber, c'est pas grave.", tag: "impératif" },
  { lvl: 4, es: "Cuídate.", fr: "Prends soin de toi.", tag: "social" },
  { lvl: 4, es: "Que tengas buen día.", fr: "Bonne journée.", tag: "social" },
  { lvl: 4, es: "Que te vaya bien.", fr: "Que ça se passe bien pour toi.", tag: "social" },
  { lvl: 4, es: "Suerte con eso.", fr: "Bonne chance avec ça.", tag: "social" },
  { lvl: 4, es: "Avísame cuando puedas.", fr: "Préviens-moi quand tu peux.", tag: "social" },
  { lvl: 4, es: "Cuenta conmigo.", fr: "Compte sur moi.", tag: "social" },
  { lvl: 4, es: "No te preocupes por eso.", fr: "Ne t'inquiète pas pour ça.", tag: "social" },
  { lvl: 4, es: "Tómate tu tiempo.", fr: "Prends ton temps.", tag: "social" },
  { lvl: 4, es: "Piénsatelo bien.", fr: "Réfléchis-y bien.", tag: "social" },

  // ---------- N5 · IDIOMATIQUE : parler comme un natif ----------
  { lvl: 5, es: "Vale.", fr: "OK.", tag: "argot", note: "Le mot le plus prononcé d'Espagne." },
  { lvl: 5, es: "Venga, vale.", fr: "Allez, OK.", tag: "argot" },
  { lvl: 5, es: "¡Qué guay!", fr: "Trop cool !", tag: "argot" },
  { lvl: 5, es: "¡Qué fuerte!", fr: "C'est dingue !", tag: "argot" },
  { lvl: 5, es: "¡No me digas!", fr: "Sans blague !", tag: "argot" },
  { lvl: 5, es: "¿En serio?", fr: "Sérieux ?", tag: "argot" },
  { lvl: 5, es: "Qué va.", fr: "Mais non, pas du tout.", tag: "argot" },
  { lvl: 5, es: "Ni de broma.", fr: "Même pas en rêve.", tag: "argot" },
  { lvl: 5, es: "Me da pereza.", fr: "J'ai la flemme.", tag: "argot" },
  { lvl: 5, es: "Estoy hasta las narices.", fr: "J'en ai ras-le-bol.", tag: "argot" },
  { lvl: 5, es: "Me estás tomando el pelo.", fr: "Tu te fous de moi.", tag: "argot" },
  { lvl: 5, es: "Se me hace tarde.", fr: "Ça se fait tard pour moi.", tag: "argot" },
  { lvl: 5, es: "Estoy flipando.", fr: "Je suis en train d'halluciner.", tag: "argot" },
  { lvl: 5, es: "Menos mal.", fr: "Heureusement.", tag: "argot" },
  { lvl: 5, es: "Por si acaso.", fr: "Au cas où.", tag: "argot" },
  { lvl: 5, es: "De repente.", fr: "Tout à coup.", tag: "connecteur" },
  { lvl: 5, es: "Cada vez más.", fr: "De plus en plus.", tag: "connecteur" },
  { lvl: 5, es: "A ver qué pasa.", fr: "On verra bien ce qui se passe.", tag: "argot" },
  { lvl: 5, es: "Ya te digo.", fr: "Grave. / Comme tu dis.", tag: "argot" },
  { lvl: 5, es: "Tal cual.", fr: "Exactement ça.", tag: "argot" },
  { lvl: 5, es: "Ni idea, tío.", fr: "Aucune idée, mec.", tag: "argot" },
  { lvl: 5, es: "Qué rollo.", fr: "Quelle galère.", tag: "argot" },
  { lvl: 5, es: "Vale la pena intentarlo.", fr: "Ça vaut le coup d'essayer.", tag: "argot" },
  { lvl: 5, es: "No tiene sentido.", fr: "Ça n'a pas de sens.", tag: "opinion" },
  { lvl: 5, es: "Me suena.", fr: "Ça me dit quelque chose.", tag: "argot" },
  { lvl: 5, es: "Se me ha ido la olla.", fr: "J'ai perdu la tête.", tag: "argot" },
  { lvl: 5, es: "Está chupado.", fr: "C'est fastoche.", tag: "argot" },
  { lvl: 5, es: "Es pan comido.", fr: "C'est du gâteau.", tag: "argot" },
  { lvl: 5, es: "Cuesta un ojo de la cara.", fr: "Ça coûte les yeux de la tête.", tag: "argot" },
  { lvl: 5, es: "Me cae bien.", fr: "Je l'aime bien.", tag: "argot", note: "Pour les gens, jamais « me gusta » — sauf si tu dragues." },
  { lvl: 5, es: "Te echo de menos.", fr: "Tu me manques.", tag: "argot", note: "Sens inversé par rapport au français." },
  { lvl: 5, es: "Vamos a dar una vuelta.", fr: "On va faire un tour.", tag: "argot" },
  { lvl: 5, es: "Ponte las pilas.", fr: "Bouge-toi.", tag: "argot" },
  { lvl: 5, es: "No te rayes.", fr: "Te prends pas la tête.", tag: "argot" },
  { lvl: 5, es: "A tope.", fr: "À fond.", tag: "argot" },
  { lvl: 5, es: "Qué pasada.", fr: "C'est ouf.", tag: "argot" },
  { lvl: 5, es: "Hace un frío que pela.", fr: "Il fait un froid de canard.", tag: "argot" },
  { lvl: 5, es: "Estoy a tope de curro.", fr: "Je suis à fond de boulot.", tag: "argot" },

  // ---------- N6 · TRAVAIL & ABSTRAIT ----------
  { lvl: 6, es: "¿Podemos agendar una reunión?", fr: "On peut caler une réunion ?", tag: "travail" },
  { lvl: 6, es: "Te envío la propuesta hoy.", fr: "Je t'envoie la proposition aujourd'hui.", tag: "travail" },
  { lvl: 6, es: "Quedamos el martes a las diez.", fr: "On dit mardi à dix heures.", tag: "travail" },
  { lvl: 6, es: "Necesito una respuesta antes del viernes.", fr: "J'ai besoin d'une réponse avant vendredi.", tag: "travail" },
  { lvl: 6, es: "¿Cuál es el presupuesto?", fr: "C'est quoi, le budget ?", tag: "travail" },
  { lvl: 6, es: "El plazo de entrega es de dos semanas.", fr: "Le délai de livraison est de deux semaines.", tag: "travail" },
  { lvl: 6, es: "Vamos a revisar los números.", fr: "On va revoir les chiffres.", tag: "travail" },
  { lvl: 6, es: "No cumplimos el objetivo.", fr: "On n'a pas atteint l'objectif.", tag: "travail" },
  { lvl: 6, es: "Hay que priorizar.", fr: "Il faut prioriser.", tag: "travail" },
  { lvl: 6, es: "Me encargo yo de eso.", fr: "Je m'occupe de ça.", tag: "travail" },
  { lvl: 6, es: "¿Quién está a cargo del proyecto?", fr: "Qui est responsable du projet ?", tag: "travail" },
  { lvl: 6, es: "Estamos retrasados con el proyecto.", fr: "On a du retard sur le projet.", tag: "travail" },
  { lvl: 6, es: "Necesitamos más recursos.", fr: "Il nous faut plus de ressources.", tag: "travail" },
  { lvl: 6, es: "La reunión se ha aplazado.", fr: "La réunion a été reportée.", tag: "travail" },
  { lvl: 6, es: "Te paso los detalles por correo.", fr: "Je t'envoie les détails par mail.", tag: "travail" },
  { lvl: 6, es: "Quedo a la espera de tu respuesta.", fr: "Je reste dans l'attente de ta réponse.", tag: "travail", note: "Formule de fin de mail, formelle." },
  { lvl: 6, es: "Perdona la demora.", fr: "Désolé pour le retard.", tag: "travail" },
  { lvl: 6, es: "¿Podrías aclararme una cosa?", fr: "Tu pourrais m'éclaircir un point ?", tag: "travail" },
  { lvl: 6, es: "En resumen, no funciona.", fr: "En résumé, ça ne marche pas.", tag: "travail" },
  { lvl: 6, es: "A largo plazo, es más rentable.", fr: "À long terme, c'est plus rentable.", tag: "travail" },
  { lvl: 6, es: "Depende del contexto.", fr: "Ça dépend du contexte.", tag: "abstrait" },
  { lvl: 6, es: "Vamos a probarlo y vemos.", fr: "On va tester et on voit.", tag: "travail" },
  { lvl: 6, es: "Tiene sentido para mí.", fr: "Ça a du sens pour moi.", tag: "abstrait" },
  { lvl: 6, es: "Me lo apunto.", fr: "Je le note.", tag: "travail" },
  { lvl: 6, es: "No es tan sencillo como parece.", fr: "Ce n'est pas aussi simple qu'il y paraît.", tag: "abstrait" },
  { lvl: 6, es: "Todo depende de cómo lo mires.", fr: "Tout dépend de comment tu le regardes.", tag: "abstrait" },
  { lvl: 6, es: "Lo importante es no rendirse.", fr: "L'important c'est de ne pas abandonner.", tag: "abstrait" },
  { lvl: 6, es: "Cada uno tiene su forma de hacerlo.", fr: "Chacun a sa façon de faire.", tag: "abstrait" },
  { lvl: 6, es: "Con el tiempo se aprende.", fr: "Avec le temps on apprend.", tag: "abstrait" },
  { lvl: 6, es: "No hay atajos.", fr: "Il n'y a pas de raccourcis.", tag: "abstrait" }
].map((c, i) => ({ id: "c" + i, ...c }));


/* ============================================================
   LE CHEAT CODE FRANCOPHONE
   Tu n'es pas à zéro. Tu connais déjà ~3000 mots espagnols.
   Ces règles les déverrouillent d'un coup.
   ============================================================ */

const RULES = [
  {
    id: "r1", title: "-tion → -ción",
    gain: 600,
    body: "Tous les noms français en -tion deviennent -ción. L'accent tombe TOUJOURS sur le o.",
    ex: [["nation", "nación"], ["situation", "situación"], ["information", "información"], ["attention", "atención"], ["révolution", "revolución"]]
  },
  {
    id: "r2", title: "-té → -dad",
    gain: 350,
    body: "Les noms abstraits féminins en -té passent en -dad. Ils restent féminins.",
    ex: [["liberté", "libertad"], ["université", "universidad"], ["réalité", "realidad"], ["difficulté", "dificultad"], ["société", "sociedad"]]
  },
  {
    id: "r3", title: "Les doubles consonnes tombent",
    gain: 400,
    body: "L'espagnol ne garde presque aucune double consonne. -ff-, -mm-, -nn-, -pp-, -tt-, -ss- entre voyelles → une seule lettre. Exceptions : ll, rr, cc (qui se prononcent différemment).",
    ex: [["difficile", "difícil"], ["professeur", "profesor"], ["appartement", "apartamento"], ["immédiat", "inmediato"], ["possible", "posible"]]
  },
  {
    id: "r4", title: "é- initial → es-",
    gain: 200,
    body: "Un mot français qui commence par é- correspond très souvent à es- en espagnol. C'est le même s latin, que le français a mangé.",
    ex: [["école", "escuela"], ["étudiant", "estudiante"], ["écouter", "escuchar"], ["état", "estado"], ["étoile", "estrella"]]
  },
  {
    id: "r5", title: "-ment → -mente",
    gain: 300,
    body: "Tous les adverbes. On les fabrique pareil : féminin de l'adjectif + -mente. Bonus : l'adjectif garde son accent écrit.",
    ex: [["rapidement", "rápidamente"], ["exactement", "exactamente"], ["normalement", "normalmente"], ["finalement", "finalmente"], ["simplement", "simplemente"]]
  },
  {
    id: "r6", title: "-ique → -ico / -ica",
    gain: 250,
    body: "Adjectifs et noms. L'accent tombe sur la syllabe d'avant, d'où l'accent écrit fréquent.",
    ex: [["politique", "político"], ["musique", "música"], ["physique", "físico"], ["public", "público"], ["magique", "mágico"]]
  },
  {
    id: "r7", title: "-ance / -ence → -ancia / -encia",
    gain: 220,
    body: "Un des transferts les plus rentables : quasiment sans exception.",
    ex: [["distance", "distancia"], ["importance", "importancia"], ["différence", "diferencia"], ["expérience", "experiencia"], ["patience", "paciencia"]]
  },
  {
    id: "r8", title: "-age → -aje",
    gain: 150,
    body: "Le -age français devient -aje, et le mot devient masculin (el).",
    ex: [["voyage", "viaje"], ["message", "mensaje"], ["garage", "garaje"], ["langage", "lenguaje"], ["personnage", "personaje"]]
  },
  {
    id: "r9", title: "ph → f",
    gain: 120,
    body: "L'espagnol a fait le ménage orthographique. Aucun ph n'a survécu.",
    ex: [["photo", "foto"], ["téléphone", "teléfono"], ["philosophie", "filosofía"], ["pharmacie", "farmacia"], ["éléphant", "elefante"]]
  },
  {
    id: "r10", title: "-eux → -oso",
    gain: 180,
    body: "Adjectifs de qualité. Féminin en -osa.",
    ex: [["curieux", "curioso"], ["généreux", "generoso"], ["délicieux", "delicioso"], ["nerveux", "nervioso"], ["fameux", "famoso"]]
  },
  {
    id: "r11", title: "-eur (métier) → -or",
    gain: 200,
    body: "Les noms d'agent. Féminin en -ora.",
    ex: [["professeur", "profesor"], ["acteur", "actor"], ["docteur", "doctor"], ["directeur", "director"], ["auteur", "autor"]]
  },
  {
    id: "r12", title: "⚠️ Les faux amis qui tuent",
    gain: 0,
    danger: true,
    body: "Ceux-là ne se déduisent pas. Ils se retiennent une bonne fois, sinon ils t'humilient en public.",
    ex: [
      ["embarazada", "ENCEINTE (pas embarrassée)"],
      ["constipado", "ENRHUMÉ (pas constipé)"],
      ["largo", "LONG (pas large)"],
      ["salir", "SORTIR (pas salir)"],
      ["ropa", "VÊTEMENTS (pas robe)"],
      ["éxito", "SUCCÈS (pas sortie)"],
      ["quitar", "ENLEVER (pas quitter)"],
      ["débil", "FAIBLE (pas débile)"]
    ]
  }
];


/* ============================================================
   PRODUCTION LIBRE — 60 s de parole, sans filet.
   ============================================================ */

const PROMPTS = [
  { lvl: 1, txt: "Présente-toi : nom, d'où tu viens, ce que tu fais.", hint: "Me llamo… Soy… Trabajo en…" },
  { lvl: 1, txt: "Commande un repas complet dans un restaurant.", hint: "Quisiera… Para beber… La cuenta…" },
  { lvl: 1, txt: "Demande ton chemin vers la gare, puis remercie.", hint: "Perdona, ¿cómo llego a…?" },
  { lvl: 2, txt: "Raconte ta journée type, du réveil au coucher.", hint: "Me levanto… Luego… Por la noche…" },
  { lvl: 2, txt: "Explique pourquoi tu apprends l'espagnol.", hint: "Estoy aprendiendo español porque…" },
  { lvl: 2, txt: "Décris la personne la plus importante de ta vie.", hint: "Es… Siempre… Me cae muy bien porque…" },
  { lvl: 2, txt: "Tu es en retard. Appelle et explique-toi.", hint: "Perdona, voy con retraso porque…" },
  { lvl: 3, txt: "Raconte le meilleur voyage que tu aies fait.", hint: "Fui a… Estuve… Lo que más me gustó fue…" },
  { lvl: 3, txt: "Raconte un truc qui t'est arrivé cette semaine.", hint: "El otro día… De repente… Al final…" },
  { lvl: 3, txt: "Parle d'un film ou d'une série que tu as adoré, et pourquoi.", hint: "Me encantó porque… Lo mejor fue…" },
  { lvl: 3, txt: "Explique un truc que tu as raté, et ce que tu en as appris.", hint: "No salió bien… Aprendí que…" },
  { lvl: 4, txt: "Si tu gagnais 10 millions demain, tu ferais quoi ?", hint: "Si tuviera… viajaría… compraría…" },
  { lvl: 4, txt: "Donne trois conseils à quelqu'un qui commence ton métier.", hint: "Yo que tú… Deberías… Es importante que…" },
  { lvl: 4, txt: "Décris où tu veux être dans cinq ans.", hint: "Espero que… Me gustaría… Habré…" },
  { lvl: 5, txt: "Défends une opinion impopulaire pendant une minute.", hint: "La verdad es que… Aunque… Sin embargo…" },
  { lvl: 5, txt: "Raconte une anecdote drôle en essayant de faire rire.", hint: "¡Qué fuerte! … Y de repente… Estaba flipando…" },
  { lvl: 6, txt: "Présente ton travail à un client hispanophone.", hint: "Nos dedicamos a… Nuestra propuesta…" },
  { lvl: 6, txt: "Explique un problème au boulot et propose une solution.", hint: "El problema es que… Yo propondría…" }
];


/* ============================================================
   ÎLOTS DE FLUIDITÉ (méthode Shekhtman)
   6 monologues à toi, polis jusqu'à la perfection.
   Tu les sors sans réfléchir → tu as l'air fluide dès le mois 1.
   ============================================================ */

const ISLANDS = [
  { id: "i1", title: "Qui je suis", brief: "30 s. Nom, origine, où tu vis, un détail qui accroche.", why: "La question arrive dans 100 % des premières conversations." },
  { id: "i2", title: "Ce que je fais", brief: "40 s. Ton métier expliqué simplement, sans jargon.", why: "Deuxième question systématique. Prépare-la, ne l'improvise jamais." },
  { id: "i3", title: "Pourquoi j'apprends l'espagnol", brief: "30 s. Ta raison, vraie et personnelle.", why: "On te la posera à chaque fois. Une bonne réponse crée un lien immédiat." },
  { id: "i4", title: "Ma journée type", brief: "45 s. Du réveil au coucher, au présent.", why: "Entraîne tout le présent + les verbes pronominaux d'un coup." },
  { id: "i5", title: "Mon histoire", brief: "60 s. Un truc qui t'est arrivé, avec un début, un pic, une fin.", why: "Verrouille le passé. Et une anecdote te rend mémorable." },
  { id: "i6", title: "Ce que j'en pense", brief: "60 s. Une opinion tranchée sur un sujet qui te tient.", why: "Débloque l'argumentation : connecteurs, nuance, subjonctif." }
];
